python/thunder/rdds/fileio/seriesloader.py, python/thunder/rdds/images.py, python/thunder/utils/common.py, python/thunder/utils/context.py
add check for existing directory when overwrite=False before running series conversion jobs.
Resolves #76.
=> check directory early when overwrite=False

python/test/test_timeseries.py, python/thunder/rdds/timeseries.py
Added a new option -- 'window-fast' -- to TimeSeries.normalize()
This is similar to the 'window' option, except that interpolation during the percentile computation is avoided by no using the numpy.percentile() method. Instead, the index within the window that is closest to the desired percentile is computed ahead of time. Then each window is sorted and this index is retrieved. Also updated the warning message for when widow size is set but user is not using one of the two windowed methods.
=> Windowed normalize optimization

python/test/test_timeseries.py, python/thunder/rdds/timeseries.py
Speeds up the window-fast option just added in #83 using `scipy.ndimage.filters.percentile_filter`. 
I compared the windowed normalization techniques using a timeseries of length 50,000 and a window of 1,000:
````
window: 4.05s
window-fast-old: 2.64s
window-fast-new: 785ms
```
So we get a speedup of around 3x over the `window-fast` method in #83, and 5x over the original `window` method. These speedups were about the same over other window lengths (50, 500, 5000).
=> Faster windowed normalization

python/thunder/rdds/fileio/imagesloader.py, python/thunder/rdds/fileio/seriesloader.py, python/thunder/utils/common.py
Old PIL does not load images correctly in Spark using the new-style `array(pilimg)` syntax, however the new pillow module appears to handle this correctly. Here fall back to matplotlib's old `pil_to_array` conversion if we detect that we've got PIL but not pillow installed.
Without this PR, loading tifs (at least single-page tifs, possibly others) with PIL 1.1.7 leads to results like the following:
```python
In [15]: data = tsc.loadImages('/path/to/tifs/', inputformat='tif-stack')
In [16]: data.first()[1].shape
Out[16]: (1, 1, 1)
In [17]: data.first()[1]
Out[17]: array([[[ <PIL.TiffImagePlugin.TiffImageFile image mode=I;16 size=512x512 at 0x3B02B00>]]], dtype=object)
```
=> add back pil_to_array function for use with old versions of PIL

python/test/test_readers.py, python/thunder/rdds/fileio/imagesloader.py, python/thunder/rdds/fileio/readers.py, python/thunder/rdds/fileio/seriesloader.py, python/thunder/utils/common.py, python/thunder/utils/context.py
This PR adds a 'recursive' keyword to all the image data input methods (basically, any time tifs or binary stacks are loaded from disk). If `recursive==True`, then the read methods will descend through a directory tree rooted at the passed `datapath` path, and try to load all files found in that tree with the specified file extension.
* This only works for reading from the local file system - specifying `recursive=True` when reading from S3 will result in an apologetic `NotImplementedError`.
* It also exposes an `ext` (extension) keyword argument on the `ThunderContext` object, allowing non-standard file extensions to be easily specified. Previously, to load flat binary image stacks with any extension other than "stack" (such as "bin"), one would have to manually create an ImagesLoader …
=> Nested directory reading

python/test/test_series.py, python/thunder/rdds/series.py
This PR adds two closely-related methods to Series objects, `meanOfRegion` and `meanByRegions`. These calculate the average time series within a set or sets of Series records specified by their keys.
=> Aggregate regions

python/test/test_data.py, python/thunder/rdds/data.py
The __getitem__ method on Data objects now raises an KeyError if a value is not found for the given
key. Previously it returned None.  The Data unit tests have been updated accordingly.
=> Changed bracket behavior for Data

python/test/test_images.py, python/test/test_series.py, python/thunder/rdds/data.py, python/thunder/rdds/images.py, python/thunder/rdds/series.py
This PR expands on the functionality introduced in PR #95, adding support for specifying regions via an array mask on the Series mean of/by region(s) methods, and adding a `meanByRegions` method on Images. 
The new images method currently returns Images where each record value is a 1 x N array, with N being the number of regions specified. This can then be converted into time series values via the usual `images.toSeries().collect()` dance, which should run very quickly since after the aggregation into regions there should be almost no data left. :) The Images meanByRegions method supports region specification either by a mask array or by passing a sequence of sequences of indices, as in the equivalent Series method.
=> Son of Aggregate regions: this is really aggregating

python/test/test_data.py, python/thunder/rdds/data.py, python/thunder/rdds/series.py, python/thunder/rdds/spatialseries.py
This PR reorganizes support for sorting outputs, 
A couple key changes / hopefully improvements:
* The primary sorting behavior is relegated to a `Data` method `sortByKey()` that calls the underlying Spark RDD functions. This will make it easier to maintain / modify the sorting behavior and use it elsewhere.
* By using this function, sorting during `Series.pack()` is now done with RDD functions, which avoids an error by which collecting the keys and values separately (for driver-side sort) can yield different orderings.
* The `collect`, `collectAsArray`, `collectValuesAsArray`, and `collectKeysAsArray` methods all now take `sorting` as an input argument. This has previously been an option on `pack`, but it is useful as an option on these functions for non-contiguous data (as reported by …
=> Modified sorting

python/test/test_seriesloader.py, python/thunder/factorization/nmf.py, python/thunder/rdds/data.py, python/thunder/rdds/fileio/imagesloader.py, python/thunder/rdds/fileio/readers.py, python/thunder/rdds/fileio/seriesloader.py, python/thunder/rdds/fileio/writers.py, python/thunder/rdds/images.py, python/thunder/rdds/imgblocks/blocks.py, python/thunder/rdds/matrices.py, python/thunder/rdds/series.py, python/thunder/utils/common.py, python/thunder/utils/context.py
This is a revision of PR #114, with a single squashed commit replacing the series of commits on that PR. This PR has also been revised since the previous to remove the `awsCredentials` attribute from `Data` objects, as discussed. The original comment from PR #114 is below, with a comment about propagating these settings to child Data objects removed.
-----
AWS credentials are required to access S3. Typically these credentials end up in two locations - first, they're put in a `core-site.xml` file, where they're read out and used by the Hadoop InputFormat readers, which in Thunder primarily come in when reading binary Series data. For other access to S3, we use the `boto` module, which looks for credentials in a couple different places, including environment variables and a `.boto` config …
=> add setAWSCredentials method on ThunderContext

python/thunder/rdds/fileio/readers.py
This PR enables the `recursive=True` flag when reading from S3. Previously this would have thrown a NotImplementedError.
After this change, loads like the following (which hits multiple nested directories in S3) appear to be working as expected:
```python
imgs = tsc.loadImages("s3n:///neuro.datasets/svoboda.lab/tactile.navigation/1/images-binary/", inputFormat="stack", ext="bin", recursive=True, stopIdx=654, dims=(512, 512, 4))
```
=> S3 reads with recursive=True

python/test/test_data.py, python/thunder/rdds/data.py
This PR adds support for numpy and python scalars as values of Data records in `Data.astype()`. Fixes #121.
=> Casting scalars

.travis.yml
This PR changes our Travis build to use Miniconda, a light-weight installation of Anaconda, which will make it easier to maintain recent versions of scientific libraries on our Travis builds, and matches the environment in which many users use Thunder fairly well.
Fixes #138
=> Conda on Travis

python/requirements.txt, python/thunder/utils/ec2.py
This PR modifies the Thunder EC2 scripts to install Anaconda. Based on discussions with @broxtronix and an earlier PR from @npyoung, this appears to be the most straigtforward way to get a newer version of Python (2.7) and more up-to-date scientific packages (newer versions of numpy, scipy, scikit-learn, and libraries that require 2.7, like seaborn) on our EC2 clusters. This also makes the EC2 installation better matched to our Travis builds (which now also use Anaconda).
We also added features for supressing the excessive output in earlier versions of the scripts, and giving simpler and cleaner indications of progress:
This did require adding one minor dependency (termcolor).
I've tested this script by launching small EC2 clusters and loading example data in Thunder, using both Spark 1.2 …
=> Anaconda on EC2

python/thunder/factorization/ica.py, python/thunder/factorization/pca.py, python/thunder/factorization/svd.py, python/thunder/rdds/data.py
This PR attempts to clarify the documentation in the factorization classes `thunder.factorization.ica`, `thunder.factorization.pca`, and `thunder.factorization.svd` by adding text in the docstrings for these functions that detail the different options for the kwarg `svdMethod`. 
This PR also attempts to clarify the documentation for statistical methods on the `data` class, e.g., `data.mean()`, by indicating in their docstrings that these methods are computed over keys and that output is returned as an ndarray.
I also fixed a few small typos.
=> updated documentation in data.py, svd.py, ica.py, and pca.py and fixed some typos

python/test/test_images.py, python/thunder/rdds/images.py
The current version of localCorr, implemented in the SpatialSeries class, requires a significant amount of data duplication and shuffling, most of which can be optimized away. This version, suggested by @sofroniewn and @d-v-b, first does spatial averaging on an Images dataset, then appends the averaged data to the original before computing the correlation in time (by first converting to a Series and then correlating the first half of the series with the second). 
The localCorr unit tests have been ported from test_spatialseries.py to test_images.py, and all the relevant ones pass.
=> Image-based local correlation

python/test/test_block_methods.py, python/thunder/extraction/block/methods/sima.py, python/thunder/extraction/extraction.py
I've created a simple BlockMethod/BlockAlgorithm pair that should allow any sima segmentation strategy to be run on a thunder block. Included is a single test case, which only runs if sima is installed. The test case passes on my laptop.
On a related note, I may try to simplify the dependencies of SIMA a bit so that it might be made a dependency of thunder without much pain. The current dependencies are:
Python 2.7
numpy >= 1.6.2
scipy >= 0.13.0
scikit-image >= 0.9.3
scikit-learn >= 0.11
shapely >= 1.2.14
pillow >= 2.6.1
future
@freeman-lab Let me know which ones you think would have to best converted to optional dependencies prior to making sima a thunder dependency.
=> BlockMethod to run any SIMA segmentation strategy

python/thunder/utils/ec2.py
New in 1.4.0, they changed the way they did AMI discovery.  See:  https://github.com/apache/spark/commit/b884daa58084d4f42e2318894067565b94e07f9d
Essentially, it relies on a default parameter that we didn’t have.  I followed the examples from the other parameters and added the default in line. 
I am spinning up clusters now, it got further than it did before, but they’re not up yet.  If they don’t spin up, I’ll post a comment.  @freeman-lab
=> Add in spark-ec2-git-repo and spark-ec2-git-branch default parameters

python/thunder/utils/context.py
This PR sets the default based on the number of cores, rather than the number of images. In practice, this significantly speeds up reductions (by avoiding excess partitioning), and has no apparent cost to subsequent performance, though this should be evaluated with additional testing.
=> Change default image partitioning

python/thunder/rdds/data.py
This PR changes the core aggregation functions to use `treeReduce` instead of `reduce`. In large-scale testing, this change improved performance by anywhere from a factor of 2-5x when performing reductions (e.g. `sum`) on very large records (each individual record 200-500 MB), without noticeably affecting performance on reduces with much smaller records.
Initial testing suggests that this change may also eliminate various memory-related errors we were encountering on large reduces, but further testing is required to confirm.
=> Use tree reduce for aggregation

setup.py
@freeman-lab `python setup.py install` fails on master due to these two lines which don’t exist in the source tree anymore.  Seems to work if I drop them- is there anything else that needs to change in this file?  I’ll tack it on if so.
=> remove dead packages in setup.py

.travis.yml
Tests should all be running on the latest Spark release (1.4.1), this PR ensures we're testing against the latest on Travis.
=> Switch travis to Spark 1.4.1

bin/setup-notebook-ec2-sshtunnel
Issue #152 was fixed in setup-notebook-ec2, but not setup-notebok-ec2-sshtunnel.  This quick pull request fixes the same bug in setup-noteboke-ec2-sshtunnel.
-Aaron
=> Fixed related to issue #152: "Notebook pylab error on ec2"

.travis.yml
Updates the version of Spark to 1.5.0. All tests with 1.5.0 run fine locally, but let's confirm on travis as well.
=> Update spark version on travis

test/test_timeseries.py, thunder/rdds/timeseries.py
`TimeSeries.detrend(data)` can return values outside of the range of the values in `data`. This is because the `TimeSeries.detrend()` method uses the wrong indices when calling `numpy.polyfit(vector, indices)`: specifically, the indices are shifted up by one. This PR fixes this bug by shifting the indices down by one.
=> fixed indexing issue in detrending

thunder/rdds/timeseries.py
The `TimeSeries.normalize()` method currently uses the following expression for subtraction / division by baseline: 
`(y - b) / (b + 0.1)`
This PR exposes the value added in the denominator of the above expression as a kwarg, termed `offset`, to `TimeSeries.normalize()`. `offset` defaults to 0.1. 
normalization is now down thus:
`(y - b) / (b + offset)`
Example usage: `data.normalize(method='linear', offset=.5)`
=> added offset kwarg for timeseries.py

.travis.yml, requirements.txt, test/test_series_io.py, thunder/base.py, thunder/images/images.py, thunder/images/readers.py, thunder/readers.py, thunder/series/readers.py, thunder/series/series.py, thunder/series/timeseries.py, thunder/series/writers.py, thunder/writers.py
This PR address one of the goals of #243 -- making v1.0.0 compatible both Python 2 and 3
=> Python 2 and 3 compatibility

test/test_images.py, thunder/images/images.py
Fix the implementation of local corr so it is now compatible with Thunder 1.0.0 and works in both spark and local mode. Still need to reenable the unit tests
=> 1.0.0 local corr

test/test_blocks.py, thunder/blocks/blocks.py, thunder/images/images.py
This PR adds two features to the Blocks object:
Adds a Blocks.map operation for applying array-to-array operations on a block by block basis.
Adds simple local mode support for blocks by considering the entire array to be a single block.
=> Blocks Update

requirements.txt, test/test_images.py, thunder/images/images.py
Adds a `Image.map_as_series` method that uses `Blocks` to apply a function to each series in an `Images` object and then turn the data back into an `Images` object -- avoids needing to transform the data all the way to a `Series` representation, which can be quite expensive to turn back into `Images` due to the high level of fragmentation that can occur when the total size of the spatial dimensions greatly outnumbers the size of the temporal dimension.
=> added map_as_series

thunder/images/images.py
Previous filter operations on images expanded a scalar input parameter to two dimensions instead of three dimensions thereby treating 3D volumes as a collection of 2D images. This behaviour has been changed in 1.0.0, but the docs had not yet been updated to reflect it.
This PR updates the docs to indicate there is no more special handling of scalar input parameters, and removes some unnecessary code in the gaussian_filter method
=> 1.0.0 clean up code and docs for filtering on images

thunder/base.py
Small fix to how `Base._map` functions in `local` mode. This allows the mapped function to return a singleton value (that is not wrapped in an `ndarray`) and still function. The resulting `Base.values` will still be an `ndarray` with the correct number of dimensions.
=> commiting change

test/test_series.py, thunder/series/series.py
Adds a `Series.flatten()` method that collapses all distributed axes onto a single axis.
=> Series.flatten()

thunder/blocks/blocks.py, thunder/blocks/local.py, thunder/images/images.py
Better matches naming for distributed chunked array. This is entirely internal.
=> rename local blocks to local chunks

test/test_blocks.py, thunder/blocks/blocks.py, thunder/blocks/local.py
Adds `Blocks.map_generic` which allows for general block -> object transformations.
=> Map generic

thunder/images/images.py
This PR adds a kwarg to the `images.map_as_series()` method for specifying the dtype of the `ndarray` resulting from the `blocks.map()` which underlies the `map_as_series()`.
=> added dtype kwarg to images.map_as_series()

.travis.yml
=> fix spark test on travis due to lack of py4j

thunder/base.py
forced dtype property to be of class np.dtype so str(dtype) would give correct output
=> dtype not always of class numpy.dtype

test/test_images_io.py, thunder/images/readers.py, thunder/readers.py
Alternative implementation to #279 
Thinking of adding a flag to `fromtif()` that would default to the current behavior of rising an error.
Also I am sending the warning using the `warning` module, I saw another way using the spark logger:
```python 
log4jLogger = sc._jvm.org.apache.log4j
LOGGER = log4jLogger.LogManager.getLogger(__name__)
LOGGER.warning("number of planes...")
```
@sofroniewn @freeman-lab What do you guys think?
=> tiffs with npages not dividing by pageCount will give a warning instead an error

thunder/readers.py
Trying to run
`data = td.images.fromexample(name='mouse',engine=None)`
fails due to a change from  #313  as the accessor function expects 3 params.
This PR fixes that, still don't know if related to #327
There are no tests for the BotoParallelReader, seems very hard to mock AWS.
@freeman-lab  Is there another way?
=> BotoParallelReader bug 

thunder/series/series.py
Tried to convert a series to spark mode and got an error. Looks like labels was just misspelled.
=> Fix misspelled "labels" in series.py

thunder/images/readers.py
When `discard_extra` is `False` we can now add the filename (as of #313) that it happened in for better debugging.
=>  Add filename to error message when multi page tif has wrong number of planes

thunder/images/images.py
=> bug fix in images.toseries() 'auto' if images length > 100000

thunder/base.py
As part of https://github.com/thunder-project/thunder-docs/pull/5
=> Doc changes to Base and Data classes

test/test_images.py, test/test_series.py, thunder/images/images.py, thunder/series/series.py
implements #335 for `Series` and a corresponding function for `Images`
=> adds reshaping functions to Images and Series

requirements.txt, test/test_images_io.py, thunder/images/readers.py, thunder/images/writers.py
This PR switches to use `tifffile` for tif writing which means we can remove the dependency on `skimage` (we were only using it for its tif handling).
This means that `images.totif` now supports 8-bit and 16-bit data and both single and multi page tifs.
cc @sofroniewn @boazmohar @d-v-b
=> replace skimage with tiffile

.travis.yml, requirements.txt
Cleans up our dependency handling by removing unused packages from the `conda` install step on `travis` so we can properly check dependencies.
=> remove unused conda installs

thunder/images/images.py
When first dimension of the images object is > 1e5 the chunk size is 0 same as #347
=> Bug fix for images.toblocks()

.travis.yml, README.md
=> Update for Travis CI to test against spark 2.0

test/test_images_io.py, test/test_readers.py, thunder/readers.py
Solves #341 
@freeman-lab What is a good default behavior as this is implemented now, it will not enable you to select either tif or tiff from your folders.
I could change the default `ext='tif'` to `'ext='tifs' to make it possible, What do you think?
Also didn't test with s3, any thoughts as to how?
=> Adds tiff files when using images.fromtif default 'tif extension
