- python/thunder/rdds/series.py
fixes thunder-project/thunder#90
> fixed error in Series.subToInd doc-string

- python/test/test_regression.py
- python/test/test_series.py
- python/thunder/decoding/uniclassify.py
- python/thunder/rdds/series.py
All the setter does is type-check and then set, so I didn't think a unit test was terribly necessary. But if we want one, I can add it. I'll just how to figure out how to assert that the correct exception is being raised...
> Series index setter

- python/thunder/rdds/images.py
extended exportAsPngs to include support for contrast adjustment and colourmap assignment
> add cmap and Vmin/Vmax to exportAsPngs

- python/thunder/utils/context.py
- python/thunder/utils/datasets.py
Implemented generation of sample data coming from a factor analysis model.
Changed the sample data keys to make things a bit cleaner.
> Factor analysis and 1D Sample Data

- python/thunder/utils/context.py
- python/thunder/utils/datasets.py
This allows generating high dimensional example data which
comes from a lower dimensional subspace. Originally I intended
to implement factor analysis, but I think this new example data is
useful on its own.
> Implement sample data from factor analysis model.

- python/thunder/extraction/source.py
added pull request for changes to extraction/source.py that include basic distance metrics for sources
> Pull request for basic distance and overlap methods between sources

- python/thunder/utils/datasets.py
This allows the generation of matrices where every element
comes from a standard normal distribution.
> Add RandomData example data generation.

- thunder/viz/colorize.py
Implements #193.  No tests for Colorize?
> add axis arg to Colorize.tile()

- thunder/rdds/fileio/readers.py
Saves the user from having to copy files to a single local directory if their data is spread across a file system and they already have a list
> Update to create a rdd from a list of images

- thunder/utils/ec2.py
Simple fix for ipynb support.
@freeman-lab @jwittenbach @sophie63
> Add jupyter install to ec2 scripts

- bin/thunder
> Enhance thunder exe script help string

- test/test_series.py
- thunder/series/series.py
> update to Series.between inclusion behavior

- test/test_base.py
- thunder/base.py
Simple fix to make sure reduce doesn't eliminate singleton dimensions.
> keep singleton dimensions on reduce

- README.md
- bin/setup-notebook-ec2
- bin/setup-notebook-ec2-sshtunnel
- doc/source/deployment.rst
- doc/source/faq.rst
- thunder/utils/ec2.py
> DOC: iPython => IPython

- thunder/images/readers.py
- thunder/series/readers.py
> adds int key handling to fromrdd

- thunder/base.py
> Missing split argument for BoltArraySpark in base.element_wise

- thunder/series/readers.py
> allows series.fromrdd to infer npartitions from shape

- test/test_series_io.py
- thunder/series/writers.py
> fixes reversed ordering in series binary writer

- requirements.txt
- test/test_base.py
- thunder/base.py
- thunder/images/images.py
- thunder/series/series.py
> base.repartition() is missing a sortByKey() to the RDD

- test/test_blocks.py
- test/test_images.py
- test/test_series_io.py
- thunder/blocks/local.py
- thunder/images/images.py
- thunder/series/writers.py
> Blocking scheme update

- test/test_base.py
- thunder/images/images.py
- thunder/series/series.py
added `.toarray()` in images and series, added assertions in the test in base
> first returns a BoltArray instead of a ndarray

- thunder/images/images.py
- thunder/series/series.py
> 'auto' for block_size on series.toimages

- test/test_base.py
- thunder/base.py
fixed a typo
added tests for caching and uncaching
> bug fix in base iscached
